# Generated by Django 6.0.2 on 2026-04-05 07:12

import Eduverse.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduverse', '0002_subject_notes_question_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(upload_to='protected/notes/%Y/%m/%d/', validators=[Eduverse.utils.validate_file_security]),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protected/questions/%Y/%m/%d/', validators=[Eduverse.utils.validate_file_security]),
        ),
    ]
