# Generated by Django 6.0.2 on 2026-05-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduverse', '0004_user_phone_number_phoneverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
